### ISSUE TITLE
翻译疑问

### ISSUE THREAD

**Issue by transtone** [wxyyxc1992/Web-Development-And-Engineering-Practices#1]
`在学习这些的时候不要太担心自己会忘了，反正记不住。你应该着重于记录这些并且理解HTML和CSS是怎么工作的。`

这句话有点不通，`这些`   一词指代不明。 `反正记不住`  和    `记录这些`   ，到底是记呢，还是不记呢，还是做笔记呢？

还有这些句子：

 `它会教你基本上关于排版的所有东西` 改成 `基本上它会教你关于排版的所有东西` 或 `它会教你关于排版的几乎所有东西` 

`到这里你应该已经明白了HTML与CSS的基本使用` 改成 `到这里你应该已经明白了HTML与CSS的基本使用方法` 或 `到这里你应该已经明白了HTML与CSS的基本用法`

`I use the term “experiments” because in experiments, you learn as much from your failure as you do from your success.` 译成 
`我是把它们形容成实验，所以不要害怕失败。` 改成 `我用了"实验"这个词，因为在实验失败中学到的经验和在实验成功中学到的一样多。`

`这嘎达` ，  `这疙瘩`? 

会不会好点？

**Comment by wxyyxc1992** [comment]
楼主看的真仔细，我翻译的时候有很多确实口语化指代不明，我稍等下会根据楼上提示做出修正
