### ISSUE TITLE
求助，在项目scss文件中，import msp.scss文件报错

### ISSUE THREAD

**Issue by unssnu** [wxyyxc1992/Web-Development-And-Engineering-Practices#7]
您好，我使用了Webstorm File Watcher来自动编译scss文件为css
已经使用过另一个scss文件做测试，一切正常
但是按照您的指导，引入后报错，自动生成的css文件里都是灰色的Backtrace
我使用了vue-cli webpack模板，在src中建立了sass文件夹，建立common.scss文件，@import "~mobile-style-preset/msp.scss";

错误提示：
cmd.exe /D /C call C:/Ruby24-x64/bin/scss.bat --no-cache --update common.scss:common.css
      error common.scss (Line 1: File to import not found or unreadable: ~mobile-style-preset/msp.scss.)

Process finished with exit code 1

请问是路径问题吗？改过几种，都还是失败，能否请您帮助一下，多谢！

**Comment by wxyyxc1992** [comment]
是的，应该是路径问题；建议你将项目中的 scss 文件拷贝到你的项目目录下；或者使用 Webpack 等进行导入。

**Comment by unssnu** [comment]
您好，已经解决了，安装三步骤中，不修改webpack的配置即可。。。。
