### ISSUE TITLE
READ.md上面的图片加载显示不全

### ISSUE THREAD

**Issue by kanting** [wxyyxc1992/Web-Development-And-Engineering-Practices#8]
READ.md上的Web知识图谱的图片显示不全

**Comment by kanting** [comment]
每次加载都只能显示一部分。。发现之前的issue有说过图片的问题。。。

**Comment by wxyyxc1992** [comment]
我本地也会出现，初步检查应该是图片太大，然后 github 在国内流量感觉也是卡卡的，所以导致有时候加载不出来。也可以直接复制图片地址或者查看原文中的地址，我稍后也把地址提出来
